"""phase2_vendor_tax_invoice_approval_scenario_tables

Revision ID: 14d3d382c16c
Revises: a407d9456dbd
Create Date: 2026-05-09 00:53:18.006052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '14d3d382c16c'
down_revision: Union[str, None] = 'a407d9456dbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('min_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('max_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('required_approvers', sa.Integer(), nullable=False),
    sa.Column('auto_approve_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('categories', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ap_ws_active', 'approval_policies', ['workspace_id', 'is_active'], unique=False)
    op.create_table('invoice_sequences',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('next_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id')
    )
    op.create_table('tax_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('tax_code', sa.Enum('deductible', 'partially_deductible', 'non_deductible', 'exempt', name='taxdeductibility'), nullable=False),
    sa.Column('deduction_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('jurisdiction', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_taxcat_ws_category', 'tax_categories', ['workspace_id', 'category'], unique=True)
    op.create_table('tax_estimates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('quarter', sa.String(length=10), nullable=False),
    sa.Column('jurisdiction', sa.String(length=20), nullable=False),
    sa.Column('taxable_income', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('estimated_tax', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('effective_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('deductions_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.Enum('draft', 'filed', 'paid', name='taxestimatestatus'), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_taxest_ws_quarter', 'tax_estimates', ['workspace_id', 'quarter'], unique=False)
    op.create_table('tax_jurisdictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('tax_rates_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('filing_frequency', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_taxjur_ws_code', 'tax_jurisdictions', ['workspace_id', 'code'], unique=True)
    op.create_table('vendors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('payment_terms_days', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('tax_id', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_vendor_ws_active', 'vendors', ['workspace_id', 'is_active'], unique=False)
    op.create_index('idx_vendor_ws_name', 'vendors', ['workspace_id', 'name'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('client_email', sa.String(length=255), nullable=True),
    sa.Column('client_address', sa.Text(), nullable=True),
    sa.Column('items_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('draft', 'sent', 'paid', 'overdue', 'cancelled', 'partially_paid', name='invoicestatus'), nullable=False),
    sa.Column('issue_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paid_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recurring_config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inv_ws_client', 'invoices', ['workspace_id', 'client_name'], unique=False)
    op.create_index('idx_inv_ws_number', 'invoices', ['workspace_id', 'invoice_number'], unique=True)
    op.create_index('idx_inv_ws_status', 'invoices', ['workspace_id', 'status'], unique=False)
    op.create_table('scenarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assumptions_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_baseline', sa.Boolean(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scen_ws', 'scenarios', ['workspace_id'], unique=False)
    op.create_table('vendor_contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_vc_vendor', 'vendor_contacts', ['vendor_id'], unique=False)
    op.create_table('expense_approvals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'auto_approved', name='approvalstatus'), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['approval_policies.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ea_ws_requester', 'expense_approvals', ['workspace_id', 'requested_by'], unique=False)
    op.create_index('idx_ea_ws_status', 'expense_approvals', ['workspace_id', 'status'], unique=False)
    op.create_table('invoice_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payment_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('reference', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_invpay_invoice', 'invoice_payments', ['invoice_id'], unique=False)
    op.create_table('sensitivity_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('scenario_id', sa.UUID(), nullable=False),
    sa.Column('variable_name', sa.String(length=100), nullable=False),
    sa.Column('range_min', sa.Float(), nullable=False),
    sa.Column('range_max', sa.Float(), nullable=False),
    sa.Column('steps', sa.Integer(), nullable=False),
    sa.Column('results_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sa_scenario', 'sensitivity_analyses', ['scenario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sa_scenario', table_name='sensitivity_analyses')
    op.drop_table('sensitivity_analyses')
    op.drop_index('idx_invpay_invoice', table_name='invoice_payments')
    op.drop_table('invoice_payments')
    op.drop_index('idx_ea_ws_status', table_name='expense_approvals')
    op.drop_index('idx_ea_ws_requester', table_name='expense_approvals')
    op.drop_table('expense_approvals')
    op.drop_index('idx_vc_vendor', table_name='vendor_contacts')
    op.drop_table('vendor_contacts')
    op.drop_index('idx_scen_ws', table_name='scenarios')
    op.drop_table('scenarios')
    op.drop_index('idx_inv_ws_status', table_name='invoices')
    op.drop_index('idx_inv_ws_number', table_name='invoices')
    op.drop_index('idx_inv_ws_client', table_name='invoices')
    op.drop_table('invoices')
    op.drop_index('idx_vendor_ws_name', table_name='vendors')
    op.drop_index('idx_vendor_ws_active', table_name='vendors')
    op.drop_table('vendors')
    op.drop_index('idx_taxjur_ws_code', table_name='tax_jurisdictions')
    op.drop_table('tax_jurisdictions')
    op.drop_index('idx_taxest_ws_quarter', table_name='tax_estimates')
    op.drop_table('tax_estimates')
    op.drop_index('idx_taxcat_ws_category', table_name='tax_categories')
    op.drop_table('tax_categories')
    op.drop_table('invoice_sequences')
    op.drop_index('idx_ap_ws_active', table_name='approval_policies')
    op.drop_table('approval_policies')
    # ### end Alembic commands ###
