"""Add currency metadata

Revision ID: a407d9456dbd
Revises: 9df63d09cc52
Create Date: 2026-05-08 23:26:16.376171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a407d9456dbd'
down_revision: Union[str, None] = '9df63d09cc52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('target_currency', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_exchange_rate_base_target_date', 'exchange_rates', ['base_currency', 'target_currency', 'date'], unique=True)
    op.create_index(op.f('ix_exchange_rates_date'), 'exchange_rates', ['date'], unique=False)
    op.alter_column('data_deletions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('data_exports', 'include_metadata',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('data_exports', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('forecast_results', sa.Column('base_currency', sa.String(length=3), server_default='USD', nullable=False))
    op.alter_column('retention_policies', 'is_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('retention_policies', 'cleanup_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('retention_policies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('retention_policies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_retention_ws_entity_unique'), table_name='retention_policies')
    op.drop_index(op.f('idx_retention_ws_entity'), table_name='retention_policies')
    op.create_index('idx_retention_ws_entity', 'retention_policies', ['workspace_id', 'entity_type'], unique=True)
    op.add_column('transactions', sa.Column('currency_code', sa.String(length=3), server_default='USD', nullable=False))
    op.add_column('transactions', sa.Column('amount_original', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('transactions', sa.Column('exchange_rate', sa.Numeric(precision=14, scale=6), nullable=True))
    op.drop_index(op.f('idx_txn_description_vec'), table_name='transactions', postgresql_ops={'description_vec': 'vector_cosine_ops'}, postgresql_with={'lists': '50'}, postgresql_using='ivfflat')
    op.alter_column('user_consents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_consents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_consents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_consents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_txn_description_vec'), 'transactions', ['description_vec'], unique=False, postgresql_ops={'description_vec': 'vector_cosine_ops'}, postgresql_with={'lists': '50'}, postgresql_using='ivfflat')
    op.drop_column('transactions', 'exchange_rate')
    op.drop_column('transactions', 'amount_original')
    op.drop_column('transactions', 'currency_code')
    op.drop_index('idx_retention_ws_entity', table_name='retention_policies')
    op.create_index(op.f('idx_retention_ws_entity'), 'retention_policies', ['workspace_id', 'entity_type'], unique=False)
    op.create_index(op.f('idx_retention_ws_entity_unique'), 'retention_policies', ['workspace_id', 'entity_type'], unique=True)
    op.alter_column('retention_policies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('retention_policies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('retention_policies', 'cleanup_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('retention_policies', 'is_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_column('forecast_results', 'base_currency')
    op.alter_column('data_exports', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('data_exports', 'include_metadata',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('data_deletions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_exchange_rates_date'), table_name='exchange_rates')
    op.drop_index('idx_exchange_rate_base_target_date', table_name='exchange_rates')
    op.drop_table('exchange_rates')
    # ### end Alembic commands ###
